#!/bin/sh

if [ -z "$BEAST" ]; then
	## resolve links - $0 may be a link to application
	PRG="$0"

	# need this for relative symlinks
	while [ -h "$PRG" ] ; do
	    ls=`ls -ld "$PRG"`
	    link=`expr "$ls" : '.*-> \(.*\)$'`
	    if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	    else
		PRG="`dirname "$PRG"`/$link"
	    fi
	done

	# make it fully qualified
	saveddir=`pwd`
	BEAST0=`dirname "$PRG"`/..
	BEAST=`cd "$BEAST0" && pwd`
	cd "$saveddir"
fi

BEAST_LIB="$BEAST/lib"
export JAVA_HOME="$BEAST/jre"

if [ -x "${JAVA_HOME}/bin/java" ]; then
  JAVA="$JAVA_HOME"/bin/java
else
  JAVA=java
fi

CPU=`uname -m`

# use BEAGLE_LIB if the BEAGLE library is not in a standard location
if [ $CPU  = 'x86_64' ]; then
  if [ -n "$BEAGLE_LIB" ]; then
	if [ -n "$BEAST_EXTRA_LIBS" ]; then
		BEAST_EXTRA_LIBS="$BEAST_EXTRA_LIBS:$BEAGLE_LIB:$JAVA_HOME/lib/amd64"
	else
		BEAST_EXTRA_LIBS="$BEAGLE_LIB:$JAVA_HOME/lib/amd64"
	fi
  fi
else  
  if [ -n "$BEAGLE_LIB" ]; then
	if [ -n "$BEAST_EXTRA_LIBS" ]; then
		BEAST_EXTRA_LIBS="$BEAST_EXTRA_LIBS:$BEAGLE_LIB"
	else
		BEAST_EXTRA_LIBS="$BEAGLE_LIB"
	fi
  fi
fi

# Explicitly add /usr/local/lib to library search path to ensure 
# beast continues to find beagle when installed here.  (This is
# necessary due to known problems with certain JREs.)
if [ $CPU  = 'x86_64' ]; then
  if [ -z "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH="/usr/local/lib:$JAVA_HOME/lib/amd64"
  else
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib:$JAVA_HOME/lib/amd64"
  fi
else
  if [ -z "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH=/usr/local/lib:$HOME/lib:$BEAST_EXTRA_LIBS   
  else
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":/usr/local/lib:$HOME/lib:$BEAST_EXTRA_LIBS   
  fi
fi


# use BEAST_EXTRA_LIBS variable to load BEAGLE and other libraries from non-default locations 
# this assumes that the library path contains all these libraries (or are set through LD_LIBRARY_PATH)
if [ -n "$BEAST_EXTRA_LIBS" ]; then 
	if [ $CPU  = 'x86_64' ]; then
	  BEAST_EXTRA_LIBS="$JAVA_HOME/lib/amd64"
	fi
fi

"$JAVA" -Dlauncher.wait.for.exit=true -Xms256m -Xmx8g -Djava.library.path="$LD_LIBRARY_PATH" -Duser.language=en -cp "$BEAST_LIB/launcher.jar" beast.pkgmgmt.launcher.BeastLauncher $*
